### PR TITLE
[SWARM-1856,1884] wfswarm-rest-http-crud updates

### PR DESCRIPTION
**Pull request by sberyozkin**
1. Updated Swarm version to 2018.3.3
2. Updated parent version to 18

### CODE REVIEW

**Comment by Ladicek** [comment]
Not sure about the test failure, seems like the database maybe didn't start correctly (or soon enough?). Let's try again.

retest this please

**Comment by sberyozkin** [comment]
Trying to retest on Win, fabric8 is in no good mood, keeps failing with some websocket issue, will keep trying...

**Comment by sberyozkin** [comment]
Just managed to retest on Win/Minishift, but not sure either why the test is failing here...

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I'll just try once more and will need to investigate deeper if it still fails. retest this please

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I'm gonna investigate this now, so please expect multiple rebuild attempts :-)

retest this please

**Comment by Ladicek** [comment]
This was a regular timeout, the cluster seems to be just slow. I'll try again a couple more times.

retest this please

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
So the problem is somewhat deeper -- the WildFly Swarm application fails to reach the PostgreSQL database even if both pods are running and healthy. Trying to ping (actually `curl`, because `ping` isn't present in the Java image) the database pod from the application pod results in `No route to host`. There's nothing we can do about that in this PR, so I've just tested this locally on Minishift and I'm +1 to merging it.

**Comment by Ladicek** [comment]
retest this please

**Comment by Ladicek** [comment]
It seems it was enough to create a new OpenShift project and the networking issues were solved! In the last test run, the application was failing on `OutOfMemoryError: Metaspace`. The Red Hat OpenJDK image pre-configures max metaspace size to 100 MB, and given that WildFly Swarm is now based on WildFly 11 (which I'm pretty sure has higher metaspace demands than WildFly 10.1), I'd say we just have to raise the limit.

Could you please add the content of https://github.com/wildfly-swarm-openshiftio-boosters/wfswarm-rest-http-crud/pull/32/files to this PR? (Also in the `.openshiftio/application.yaml`, please.)

**Review by Ladicek — APPROVED** [review]

**Pull request merged**
